[project]
name = "contact-use"
version = "0.1.0"
description = "Find anyone by any means necessary"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.5",
    "uvicorn>=0.32.1",
    "pydantic>=2.10.3",
    "python-multipart>=0.0.12",
    "browser-use>=0.5.6",
]
